MongoMovies/Models/Actor.cs
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Models
{
    public class Actor
    {
        [BsonElement("name")]
        public string ActorName { get; set; }

        [BsonElement("facebook_likes")]
        public int FacebookLikes { get; set; }
    }
}

MongoMovies/Models/ErrorViewModel.cs
using System;

namespace MongoMovies.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MongoMovies/Models/Movie.cs
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Models
{
    [BsonIgnoreExtraElements]
    public class Movie
    {
            [BsonElement("movie_title")]
            public string MovieTitle { get; set; }

            [BsonElement("title_year")]
            public int TitleYear { get; set; }

            [BsonElement("color")]
            public string Color { get; set; }

            [BsonElement("director_name")]
            public string DirectorName { get; set; }

            //[BsonElement("num_critic_for_reviews")]
            //public int NumCriticForReviews { get; set; }

            //[BsonElement("duration")]
            //public int Duration { get; set; }

            //[BsonElement("gross")]
            //public int Gross { get; set; }

            //[BsonElement("director_facebook_likes")]
            //public int DirectorFacebookLikes { get; set; }

            //[BsonElement("num_voted_users")]
            //public int NumVotedUsers { get; set; }

            //[BsonElement("cast_total_facebook_likes")]
            //public int CastTotalFacebookLikes { get; set; }

            //[BsonElement("facenumber_in_poster")]
            //public int FacenumberInPoster { get; set; }

            [BsonElement("movie_imdb_link")]
            public string MovieImdbLink { get; set; }

            //[BsonElement("num_user_for_reviews")]
            //public int NumUserForReviews { get; set; }

            [BsonElement("language")]
            public string Language { get; set; }

            [BsonElement("country")]
            public string Country { get; set; }

            [BsonElement("content_rating")]
            public string ContentRating { get; set; }

            //[BsonElement("budget")]
            //public int Budget { get; set; }

            //[BsonElement("imdb_score")]
            //public int ImdbScore { get; set; }

            //[BsonElement("movie_facebook_likes")]
            //public int MovieFacebookLikes { get; set; }

            [BsonElement("genres")]
            public List<string> Genres { get; set; }

            [BsonElement("actors")]
            public List<Actor> Actors { get; set; }

        }
    }

MongoMovies/Models/MovieSimple.cs
using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Models
{
    [BsonIgnoreExtraElements]
    public class MovieSimple
    { 
        [BsonElement("movie_title")]
        public string MovieTitle { get; set; }

        [BsonElement("title_year")]
        public int TitleYear { get; set; }

        [BsonElement("genres")]
        public List<string> Genres { get; set; }

        [BsonElement("actors")]
        public List<Actor> Actors { get; set; }

    }
}

MongoMovies/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MongoMovies.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MongoMovies/Controllers/MovieController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using MongoMovies.Data;
using MongoMovies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Controllers
{
    public class MovieController : Controller
    {
        #region Fields

        private readonly MongoConnector _connector;

        #endregion
        #region Constructors

        public MovieController(MongoConnector connector)
        {
            _connector = connector;
        }

        #endregion

        #region Actions

        public IActionResult Index()
        {
            // connection string
            // Pattern 1 : mongodb://HOST:PORT/DATABASE
            //             mongodb://localhost:27017/imdb
            var connectionString = "mongodb://localhost:27017/imdb";

            // MongoDB client
            var mongoClient = new MongoClient(connectionString);

            // Use database (use imdb)
            var mongoDatabase = mongoClient.GetDatabase("imdb");

            // The Movie collection
            // "movies" : the name of the MongoDB collection 'on the Mongo server)
            // MovieSimple : the type of .NET objects to retrieve from the collection
            var movieCollection = mongoDatabase.GetCollection<MovieSimple>("movies");


            // Count movies
            var total = movieCollection.CountDocuments(m => m.TitleYear == 2010);
            var total2 = movieCollection.CountDocuments(m => true);

            // Test
            ViewBag.Message = "Co ok";
            ViewBag.Total = total;
            ViewBag.Total2 = total2;

            return View();
        }

        public IActionResult AMovie()
        {
            var movieCollection = _connector.Database.GetCollection<Movie>("movies");

            // the first movies
            var movies = movieCollection
                .Find(m => true)
                .SortBy(m => m.MovieTitle)
                .ToList();

            //render View
            ViewBag.Movies = movies;
            return View();
        }

        #endregion


    }
}

MongoMovies/Controllers/MovieSimpleController.cs
using Microsoft.AspNetCore.Mvc;
using MongoDB.Driver;
using MongoMovies.Data;
using MongoMovies.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MongoMovies.Controllers
{
    public class MovieSimpleController : Controller
    {
        #region Fields

        private readonly MongoConnector _connector;

        #endregion
        #region Constructors

        public MovieSimpleController(MongoConnector connector)
        {
            _connector = connector;
        }

        #endregion

        #region Actions

        public IActionResult Index()
        {
            // connection string
            // Pattern 1 : mongodb://HOST:PORT/DATABASE
            //             mongodb://localhost:27017/imdb
            var connectionString = "mongodb://localhost:27017/imdb";

            // MongoDB client
            var mongoClient = new MongoClient(connectionString);

            // Use database (use imdb)
            var mongoDatabase = mongoClient.GetDatabase("imdb");

            // The Movie collection
            // "movies" : the name of the MongoDB collection 'on the Mongo server)
            // MovieSimple : the type of .NET objects to retrieve from the collection
            var movieCollection = mongoDatabase.GetCollection<MovieSimple>("movies");


            // Count movies
            var total = movieCollection.CountDocuments(m => m.TitleYear == 2010);
            var total2 = movieCollection.CountDocuments(m => true);

            // Test
            ViewBag.Message = "Co ok";
            ViewBag.Total = total;
            ViewBag.Total2 = total2;

            return View();
        }

        public IActionResult List()
        {
            var movieCollection = _connector.Database.GetCollection<MovieSimple>("movies");

            // the first movies
            var movies = movieCollection
                .Find(m => true)
                .SortBy(m => m.MovieTitle)
                .Limit(50)
                .ToList();

            //render View
            ViewBag.Movies = movies;
            return View();
        }

        #endregion


    }
}

MongoMovies/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!--<div class="text-center">-->
<div class="i">
    <style>
        body {
            background-image: url('../img/starwars.jpg');
            background-size: 100% 93%;
            /*background-size: cover;*/
            background-repeat: no-repeat;
        }
    </style>
    <div class="tImg">
        <h1 class="display-4">
            Bienvenue sur <br />
            Mongo Movies
        </h1>
        <p>Il y a longtemps, bien longtemps, dans une galaxie lointaine...</p>
    </div>
</div>

MongoMovies/Views/Movie/AMovie.cshtml
<h1>Films</h1>

<table>
    <thead>
        <tr>
            <th scope="col">Nom</th>
            <th scope="col">Année</th>
            <th scope="col">Pays</th>
            <th scope="col">Langue</th>
            <th scope="col">Note</th>
        </tr>
    </thead>
    <tbody>
        @{foreach (Movie movie in ViewBag.Movies)
            {
                <tr>
                    <td>@movie.MovieTitle</td>
                    <td>@movie.TitleYear</td>
                    <td>@movie.Country</td>
                    <td>@movie.Language</td>
                    <td>@movie.ContentRating</td>
                </tr>
            }

        }
    </tbody>
</table>

MongoMovies/Views/MovieSimple/Index.cshtml
<h1>Nombre de films</h1>

<h2>@ViewBag.Message</h2>

<h3>Nombre de films en 2010 : @ViewBag.Total</h3>

<h3>Nombre de films total : @ViewBag.Total2</h3>

MongoMovies/Views/MovieSimple/List.cshtml
<h1>50 films</h1>

<table>

    <thead>
        <tr>Nom film</tr>
        <tr>Année</tr>
    </thead>
    <tbody>
        @{foreach (MovieSimple movie in ViewBag.Movies)
            {
                <tr>
                    <td>@movie.MovieTitle</td>
                    <td>@movie.TitleYear</td>
                </tr>
            }

        }
    </tbody>
</table>

<!--

<div class="container mt-3 mb-3">
    <table class="table table-dark">
        <thead>
            <tr>
                <th scope="col">Film</th>
                <th scope="col">Année</th>
                <th scope="col">Budget</th>
                <th scope="col">recettes</th>
                <th scope="col">Durée</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
</div>
    -->

MongoMovies/Views/Partials/Layout/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - MongoMovies
        </div>
    </footer>
}

MongoMovies/Views/Partials/Layout/_Header.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - MongoMovies</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
}

MongoMovies/Views/Partials/Layout/_Navbar.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MongoMovies</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" asp-area="" asp-controller="Home" asp-action="Index">Films</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" asp-controller="MovieSimple" asp-action="Index">Nombre de films</a>
                            <a class="dropdown-item" asp-controller="MovieSimple" asp-action="List">50 films</a>
                            <a class="dropdown-item" asp-controller="Movie" asp-action="AMovie">Les films</a>
                        </div>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle text-white" data-toggle="dropdown" asp-area="" asp-controller="Home" asp-action="Index">Realisateurs</a>
                        <div class="dropdown-menu">
                            <a class="dropdown-item" href="#">Another action</a>
                            <a class="dropdown-item" href="#">Something else here</a>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="#">Separated link</a>
                        </div>
                    </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
 
                    <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Informations</a>
                   
                </form>
            </div>
        </div>
    </nav>
}

MongoMovies/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <partial name="~/Views/Partials/Layout/_Header.cshtml" />
</head>

<body>
@*Barre de navigation*@
        <partial name="~/Views/Partials/Layout/_Navbar.cshtml" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @* Pied de page *@
    <partial name="~/Views/Partials/Layout/_Footer.cshtml" />

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>